arch: convnext_small
backend: nccl
batch_size_per_gpu: 6
clip_grad: 0.3
data_path: /mnt/data/imagenet/
dist_url: env://
drop_path_rate: 0.1
epochs: 100
eval_every: 5
freeze_last_layer: 3
gamma: null
global_crops_scale: !!python/tuple
- 0.14
- 1.0
local_crops_number: 6
local_crops_scale: !!python/tuple
- 0.05
- 0.14
local_rank: 0
lr: 0.001
min_lr: 2.0e-06
mode: simpool
momentum_teacher: 0.996
nb_knn:
- 10
- 20
- 100
- 200
norm_last_layer: true
num_workers: 10
optimizer: adamw
out_dim: 65536
output_dir: /mnt/datalv/bill/logs/temp/
patch_size: 16
saveckp_freq: 20
seed: 0
subset: -1
teacher_temp: 0.07
temperature: 0.07
use_bn_in_head: false
use_fp16: false
warmup_epochs: 10
warmup_teacher_temp: 0.04
warmup_teacher_temp_epochs: 50
weight_decay: 0.04
weight_decay_end: 0.4
